version: '3'

services:
  pyautogui-container:
    build: .
    image: pyautogui-image
    container_name: pyautogui-container
    volumes:
      - .:/app
    environment:
      DISPLAY: ":99"
    command: >
      sh -c "Xvfb :99 -screen 0 1024x768x16 &
             chromium-browser --no-sandbox &
             python /app/app.py"
